export const WS_MESSAGE_TYPES = {
    FRIEND_REQUEST: 'FRIEND_REQUEST',
    FRIEND_RESPONSE: 'FRIEND_RESPONSE',
    FRIEND_ONLINE: 'FRIEND_ONLINE',
    FRIEND_OFFLINE: 'FRIEND_OFFLINE',
    NEW_MESSAGE: 'NEW_MESSAGE',
    USER_ONLINE: 'USER_ONLINE',
    USER_OFFLINE: 'USER_OFFLINE',
    MESSAGE_READ: 'MESSAGE_READ',
    TYPING: 'TYPING',
    ERROR: 'ERROR',
    CONNECTION: 'CONNECTION'
}