server:
  port: 9090


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chat_system?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: kimin
    password: kmn@68A1BH
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 2000MB



mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

file:
  upload-dir: /home/kimin/myproject/uploads
  avatar-dir: /home/kimin/myproject/uploads/avatar

