server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chat_system?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME:kimin}
    password: ${DB_PASSWORD:kmn@68A1BH}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 2000MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

file:
  upload-dir: ${UPLOAD_DIR:/home/kimin/chat_system/uploads}
  avatar-dir: ${AVATAR_DIR:/home/kimin/chat_system/uploads/avatar}

# CORS configuration
cors:
  allowed-origins: ${FRONTEND_URL:http://kimin.pink:5173}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  exposed-headers: Content-Disposition

# Application configuration
app:
  frontend-url: ${FRONTEND_URL:http://kimin.pink:5173}
